EventApi:
  eventFinderUsername: test
  eventFinderPassword: test
  eventEndPoint: http://api.eventfinder.co.nz/v2/events.json
  categoryEndPoint: http://api.eventfinder.co.nz/v2/categories.json
  locationEndPoint: http://api.eventfinder.co.nz/v2/locations.json